server:
  port: 7001
spring:
  application:
    name: spring-cloud-eureka-client01

# 单机配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka # 向指定地址注册
    fetch-registry: true # 是否拉取服务列表 (默认true)
    registry-fetch-interval-seconds: 10 # 缓解服务列表脏读问题
    healthcheck:
      enabled: true
  instance:
    hostname: localhost #服务主机名
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
    prefer-ip-address: true # 服务列表以IP形式展示

# 集群配置
#eureka:
#  client:
#    service-url:
#      defaultZone: http://eureka01:8761/eureka,http://eureka02:8762/eureka,http://eureka03:8763/eureka # 向指定地址注册
#    fetch-registry: true # 是否拉取服务列表 (默认true)
#    registry-fetch-interval-seconds: 10 # 缓解服务列表脏读问题
#    healthcheck:
#      enabled: true
#  instance:
#    hostname: localhost #服务主机名
#    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
#    prefer-ip-address: true # 服务列表以IP形式展示